
logging:
  level:
    org:
      springframework: debug

spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:billshare}
    username: ${RDS_USERNAME:admin}
    password: ${RDS_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    serialization:
      write-dates-as-timestamps: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
    database: 0



##Redis服务器地址
#  spring.redis.host=127.0.0.1
#  #Redis服务器连接端口
#  spring.redis.port=6379
#  #Redis数据库索引（默认为0）
#  spring.redis.database=0
#  #连接池最大连接数（使用负值表示没有限制）
#  spring.redis.jedis.pool.max-active=50
#  #连接池最大阻塞等待时间（使用负值表示没有限制）
#  spring.redis.jedis.pool.max-wait=3000
#  #连接池中的最大空闲连接
#  spring.redis.jedis.pool.max-idle=20
#  #连接池中的最小空闲连接
#  spring.redis.jedis.pool.min-idle=2
#  #连接超时时间（毫秒）
#  spring.redis.timeout=5000
#spring.jpa.
#  output:
#    ansi:
#      enabled: ALWAYS

jwt:
  signing:
    key:
      secret: mySecret
  get:
    token:
      uri: /authenticate
  refresh:
    token:
      uri: /refresh
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 604800
server:
  port: 8080
  address: 192.168.0.125
#  address: 192.168.86.166



path:
  avatar: /Users/pengyizhuang/Code/Java/BillShare/BillShare/src/main/resources/static/image/avatar
  receipt: /Users/pengyizhuang/Code/Java/BillShare/BillShare/src/main/resources/static/image/receipt


origins:
  allowed: "*"


